### ISSUE TITLE
Send images/attachments to contributors

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1059]
```
As an editor
I would like to be able to send an attachment, like an image
To have similar chat functionality that contributors have
```

**Comment by mattwr18** [comment]
Signal: We can send a base64 encoded attachment with [/v2/send](https://bbernhard.github.io/signal-cli-rest-api/#/Messages/post_v2_send) with `signal-cli-rest-api`

Telegram: We can send many different types of attachments, including `photo`, `audio`, `animation`, `poll`, etc. See the [docs](https://core.telegram.org/bots/api). Different from Signal, we need to use a different method for each type. See [sendPhoto](https://core.telegram.org/bots/api#sendphoto), for example.

Threema: We can send files of various types,encrypted e2e. We can also send images as images vs. files. See [docs on image sending with threema-rb](https://github.com/threemarb/threema#image) and [file sending](https://github.com/threemarb/threema#file)

Postmark: We can send attachments as well. See [docs on sending attachments](https://github.com/ActiveCampaign/postmark-rails/wiki/Email-sending#sending-attachments)

**Comment by FrauCsu** [comment]
We want to finally tackle the issue of sending out attachments (first: photos). Please join the conversation on this, @tillprochaska @phoeinx @roschaefer, so we can get to it.

**Comment by FrauCsu** [comment]
Tested the current state of sending images @mattwr18 

Our Feedback: 

1) Please tell editors, which file was attached (file name), not just show the preview of picture on the right side
2) When multiple pictures are sent, preview is broken. Should look like multiple pictures in a messenger
3) Error: When deleting text on the left, there is a blue button popping up oi the right side
4) Missing Function: remove image/attachment, maybe add an "x" to the file name as used on desktop screens for push notifications 
  
See screenshots below: 

![Bildschirm­foto 2022-11-21 um 16 57 46](https://user-images.githubusercontent.com/44811680/203101731-bd5e8207-8f90-420b-b551-dddc2fb64b59.png)
<img width="331" alt="Bildschirm­foto 2022-11-21 um 16 56 03" src="https://user-images.githubusercontent.com/44811680/203101735-8868c89a-0962-4025-9bf4-f0b92ae1c542.png">
![Bildschirm­foto 2022-11-21 um 16 55 24](https://user-images.githubusercontent.com/44811680/203101739-bd8d23d3-87e8-43b9-9cee-e2b32a187cc5.png)
![Bildschirm­foto 2022-11-21 um 16 52 11](https://user-images.githubusercontent.com/44811680/203101742-5b7d433e-186c-4d8f-9882-c0fc1e168318.png)

**Comment by mattwr18** [comment]
@FrauCsu here are my thoughts on this feedback.

1. I talked with you about displaying the filename already. The thing is that where should it appear? My idea was to not add another button to the toolbar, but have another section in the request form where we could use the same UI as we do in other places, for example in the Settings page. I thought you asked me to leave the button, so have you changed your mind, or are you asking for the name to appear somewhere else? If we add multiple files, we need to consider that it might take up a bit of space, so there should be a design that takes this into consideration.
![Screenshot from 2022-11-21 20-08-30](https://user-images.githubusercontent.com/26943915/203138605-b71a63bb-ffb4-4761-ac7e-e86b8a9743b6.png)

2. I don't know what you mean by broken. I can see from the screenshot that there is an image that doesn't display. If that is what you mean by broken, I need more information because I wasn't able to encounter this bug. If you mean the preview looks different than the screenshot you added where the images are grouped, I talked to @drjakob about this. We cannot make the preview look like the messengers because the messengers themselves render the images differently. For Threema, a message is sent for each image that is attached. For Signal and Telegram they are grouped, but don't look exactly the same, though it's close. For Postmark it is completely different than the preview, but then the preview doesn't really pretend to preview the email channel. When I discussed this with @drjakob, he told me not to spend too much time on the preview. I chose to make it look like Threema because I think it is important to consider whether it's a nice UX to send several images attached to a request given that Threema in particular does not group them and send them one at a time. There is quite a few things to consider if we want to try to group them like Signal and Telegram and we should expect that we will delay the release as a result.

3. I am not able to reproduce this error. I would need to see you use it and/or give a detailed description on how to reproduce the bug. What I have tested, in Chrome and Firefox, on staging.100ey.es is to add text, then completely delete it all. I've added some text, then attached an image, then deleted all the text, reversed the order to attache the image, then add text, then delete. I've tried highlighting and cutting the text. In all these cases, over both browsers, what happens is the default text replaces this "blue button".

4. We could add this, but it would be the first place in the app where we have this requirement. We have at least three other places where we can add images and none of them have this feature. Is there a reason we want it only here, or will we create an issue to add it elsewhere? Also, what should it look like? Depending on the answer to the 1. question, I could imagine different ways to handle it, but if we left the button in the toolbar, what should happen? If there is a file, there appears another button that has a close icon in the toolbar that would be used to clear all files from the file input field? 

5. We attempt to display the image as a 200X200 thumbnail, but if the aspect ratio is like the screenshot, it will take up more height. I'm not quite sure what to recommend, we could try to make the images smaller and if the user wants to click on the image, we can open a new tab with the full image? We could move the images out of the header, but that is where all the requests' information is.
