### ISSUE TITLE
Individualized address in requests: Hello, (name)

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1315]
As an editor
I would like to be able to address all my contributors by their name when sending out requests. Therefore I need to be able to use a button to individualize requests, displaying e.g. "Hallo ((VORNAME))"

**Comment by tillprochaska** [comment]
Our value proposition is personalized communication and sending out messages with broken placeholders would ruin that (and would probably have a negative impact on contributor engagement). Therefore, we should consider how to prevent that. A few different approaches I could imagine:

**Identifying syntax errors:** If we use some custom syntax for placeholders (e.g. `{{VORNAME}}` and an editor makes a mistake (e.g. they might use a placeholder that we do not support or they use single braces instead of double braces), we should try to warn them about this before sending out any messages („Looks like you meant to use a placeholder, did you mean `{{VORNAME}}`?”).

**Showing a preview/confirmation**: We could preview the message as it would be rendered for a random contributor. This might help editors to spot mistakes.

**Highlighting placeholder:** This helps identifying placeholders as well as non-supported placeholders/invalid syntax.

![image](https://user-images.githubusercontent.com/1512805/161588010-36a9ad56-ff71-43a0-83ec-1ba3cfbe9bf5.png)
