### ISSUE TITLE
Fetch Signal profile pictures during onboarding

### ISSUE THREAD

**Issue by tillprochaska** [tactilenews/100eyes#1429]
During Signal onboarding, new contributors have to send an initial Signal message to the instance’s 100eyes phone number. By doing this, they also explicitly grant us access to their Signal profile picture. We could/should fetch the profile picture to display it in the 100eyes contributor profile.

**Comment by drjakob** [comment]
I like the idea.

**Comment by FrauCsu** [comment]
@mattwr18 Please make this happen.

**Comment by mattwr18** [comment]
Any idea how this would work @tillprochaska ? Sounds easy, but where would we fetch the avatar from?
[signal-cli](https://github.com/AsamK/signal-cli) has a `listContacts` subcommand, which:

```
Show a list of known contacts with names and profiles.
```
But this does not include the profile pic, it lists the name, profile name, blocked status, and if message expiration is enabled or not.
There are quite a few issues asking for this as a feature, for example:  [Expose a way to retrieve a user profile avatar pic #869 ](https://github.com/AsamK/signal-cli/issues/869).

[There](https://github.com/AsamK/signal-cli/issues/869#issuecomment-1133586375) the maintainer has said:

> The avatar is not included there, but is just stored in the signal-cli config directory (avatars/profile-NUMBER).

I was able to verify that we do in fact have the profile images of signal contributors who have them in our signal containers. I used this to update existing contributors to attach their profile images as avatars.

As far as doing it in an onboarding step, since we don't receive it via message, I think we would need to add a cronjob to copy the `avatars` directory from the signal container to `/home/ansible`, then copy it to the app container before running a rake task to attach the contributors. I made some progress with this today, but just curious if you have any information that might simplify the process?

Also, one thing I noticed is that with the new changes regarding `uuid`, the avatars seem to no longer be stored as `avatars/profile-NUMBER` and instead stored as `avatars/profile-UUID`, so for this method to work, we would probably need to save the `uuid` in the `contributors` table, I guess, right?

**Comment by tillprochaska** [comment]
> As far as doing it in an onboarding step, since we don't receive it via message, I think we would need to add a cronjob to copy the avatars directory from the signal container to /home/ansible, then copy it to the app container before running a rake task to attach the contributors. I made some progress with this today, but just curious if you have any information that might simplify the process?

The directory signal-cli uses to store the avatars is already mounted as a volume in the `app` container (`/app/signal-cli-config/avatars`), so there’s no need to copy files in a cronjob.

> Also, one thing I noticed is that with the new changes regarding uuid, the avatars seem to no longer be stored as avatars/profile-NUMBER and instead stored as avatars/profile-UUID, so for this method to work, we would probably need to save the uuid in the contributors table, I guess, right?

Yes, you are correct. However, I’m not sure how we could retrieve the UUID in a clean way. It doesn’t seem to be returned when creating a contact. It is stored in `signal-cli-config/data/{{id}}.d/recipients-store`. However, I don’t think we should rely on this implementation detail.

Instead, I’d prefer to wait for the `listContacts` command to be exposed via `signal-cli-rest-api` or if we could contribute that API endpoint to `signal-cli-rest-api`.

**Comment by tillprochaska** [comment]
> Would we also want to run a daily task to keep the avatars up to date? I don't know what happens if someone changes their avatar or adds one, for example.

To be honest, I wouldn’t do that for two reasons:

1. Keep things simple.
2. We display avatars so that editors can easily recognize contributors. If the avatars change after a contributor has onboarded, it might actually make this more difficult.

(I do think that we update avatars for contributors onboarded via Telegram -- so this would be kind of inconsistent.)

> We do receive the information on each message though as part of the envelope. So, my idea would be to save the sourceUuid to the contributor record as signal_uuid and then we can use it to attach the avatars in the same way we do with the legacy numbers.

Yeah, that sounds sensible. Should be enough to do this for the initial "Hello" message from a contributor, though, as the UUID doesn’t change.

**Comment by tillprochaska** [comment]
Oh, maybe one thing to check before you go ahead and implement this:

Now that we create a signal-cli contact with the contributors phone number before we receive their first message, does signal-cli still store the avatar in `profile-{{UUID}}` instead of `profile-{{NUMBER}}`?

I remember seeing some code in signal-cli’s source that falls back to the UUID as an identifier only if the number is not available. I’m not sure, but the cases in which the avatars where stored in a file using the UUID might actually be from contributors that onboarded *before* we deployed #1428?

**Comment by tillprochaska** [comment]
I think this would be the relevant part:

1. https://github.com/AsamK/signal-cli/blob/master/lib/src/main/java/org/asamk/signal/manager/AvatarStore.java#L85

2. https://github.com/AsamK/signal-cli/blob/master/lib/src/main/java/org/asamk/signal/manager/storage/recipients/RecipientAddress.java#L53-L56

**Comment by mattwr18** [comment]
> To be honest, I wouldn’t do that for two reasons:

>   1. Keep things simple.
>  2. We display avatars so that editors can easily recognize contributors. If the avatars change after a contributor has onboarded, it might actually make this more difficult.

> (I think we update avatars whenever we receive a message for contributors onboarded via Telegram -- so this would be kind of inconsistent.)

I like both those points, but it would not be consistent with Telegram and it would also not be consistent if we work on  [Fetch Threema user-image during onboarding #1440 ](https://github.com/tactilenews/100eyes/issues/1440). I have looked into this and Threema does not store the avatar on disk anywhere, it is only sent as part of the message.

Also, it doesn't address what to do about contributors who do not have an image when they onboard, but add one later. Though, I'm not sure exactly what happens in this case. I can imagine that it is saved on the first message received from that contributor after they add an avatar, but haven't seen where this happens.

> Yeah, that sounds sensible. Should be enough to do this for the initial "Hello" message from a contributor, though, as the UUID doesn’t change.

That is where I started adding the code, just when we trigger a `CONNECT` event. Though this means that we wouldn't be able to ever add an avatar for the contributors whose avatars are saved as uuid? 

> I remember seeing some code in signal-cli’s source that falls back to the UUID as an identifier only if the number is not available. I’m not sure, but the cases in which the avatars where stored in a file using the UUID might actually be from contributors that onboarded before we deployed https://github.com/tactilenews/100eyes/pull/1428?

It's possible actually. If I look at when I onboarded to lz, the image was saved `11:34 UTC` and we received an error at `13:34 CEST` about an unknown contributor. I realized the issue and deployed the fix, deleted my contributor from the db, and re-signed up. Note that I did not remove the contact using `signal-cli`. When I signed up again, it seems that it was able to determine that it was the same contact who already had an avatar saved on disk and did not add another entry with the `-NUMBER` format.

I could test out the `removeContact`, delete from db, re-sign up and check what happens. Unfortunately, this would not be a good flow for other instances, like `echo`, where there three contributors who have their avatars saved with the `uuid` format. Maybe, some or all of those don't even have avatars and either way, I think we can live with it.

**Comment by tillprochaska** [comment]
We could adjust the existing implementation for Telegram and simply not update the avatar if the contributor already has an avatar attached. Should be a simple if statement? Same goes for Threema, I guess.

**Comment by mattwr18** [comment]
> We could adjust the existing implementation for Telegram and simply not update the avatar if the contributor already has an avatar attached. Should be a simple if statement? Same goes for Threema, I guess.

true

> In any case, maybe a good first step is to implement the job that retrieves the avatar from disk and attaches it to the contributor record, then execute it once we receive the first message? We can easily update the code to execute that job for subsequent messages as well?

agreed, almost have that implemented already. Will put in a PR today. And, I've already updated all the records on all the instances that can be updated.

Ok, so removing the contact does not delete the avatar. And, signing back up does not add a new avatar, so I guess it's a bit difficult to test unless it's a new instance? However, looking at the `echo` instance, I am fairly certain that it behaves as you described because the `3` contirbutors from `echo` were from the 2-6 of August. You deployed the fix on the 8 and since then we have had 5 contributors onboard with signal, I believe, and they all have their avatars saved with the `NUMBER` format.

Since, we can always save the `sourceUuid` with any message received, I won't add it to the db now since we don't seem to have a use for it. Interestingly, we can send out messages using the uuid instead of the number, but I think it's useful to actually save the number in case the newsroom wants to reach out to the contributor so I can\t see a benefit to sending out with the uuid.
