### ISSUE TITLE
Fetch Threema user-image during onboarding

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1440]
Threema also stores user images. Fetch it with first request if possible.

**Comment by mattwr18** [comment]
I've looked into this and discovered some things.
- Threema allows you to set a profile picutre and decide who it is shared with:
  - nobody
  - everybody you write to
  - selected contacts
- It seems not possible to fetch these profile images at onboarding since:

> To ensure privacy, profile pictures are not stored on a server, they are transmitted between users upon message exchange. Like any other content, profile pictures are end-to-end encrypted.

See [profile pictures blog](https://threema.ch/en/blog/posts/profile-pictures)

- It doesn't appear that we receive the profile image in the message using the Gateway
  - I have set a profile image for myself and shared with everyone I write to
  - sent a message to my locally running server and cannot find the image anywhere
  - According to the docs incoming messages contain:
    - `from` sender identity (8 characters)
    - `to` your API identity (8 characters, usually starts with '*')
    -  `messageId` message ID assigned by the sender (8 bytes, hex encoded)
    - `date` message date set by the sender (UNIX timestamp)
    - `nonce` nonce used for encryption (24 bytes, hex encoded)
    - `box` encrypted message data (max. 4000 bytes, hex encoded)
    - `mac` Message Authentication Code (32 bytes, hex encoded, see below)
    - `nickname` public nickname of the sender, if set
  - I have checked with our implementation and this is what I can see as well.
- I checked the python, php, rust implementations and none of them seem to reference any way of downloading and saving a profile image.

@drjakob Moving forward, we could send a message to Threema to ask them if in fact we do not receive the image with the e2e messages and if not why?

**Comment by tillprochaska** [comment]
Hi @mattwr18, someone had the same questions in [this (German) thread](https://threema-forum.de/index.php?thread/3739-profilbild-freigabe-bekommen-threema-gateway-accounts-das-profilbild/) from the Threema forum. A user that seems to be a Threema representative replied that this is not possible. That has been in 2018 and things might have changed, so I think contacting Threema to confirm this is a good idea!

**Comment by mattwr18** [comment]
I have sent an email to Threema support about this and another issue and will update here with their response.

**Comment by mattwr18** [comment]
Threema support got back to me and said:

> Dear Mr. Rider,
> 
> Thank you for your patience. I am glad to answer your questions as follows.
> 
> ...
> 
> Furthermore, profile pictures aren't sent to the gateway ID.
> 
> I hope this information is useful. Should you have further questions, don't hesitate to
> contact us again.

So, unfortunately, we will not be able to provide this feature for our Threema contributors. Closing the issue. It can always be re-opened if they decide to change their policy.
