### ISSUE TITLE
Add 100eyes Logo to Authy

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#1582]
As an editor I want to have the 100eyes logo in my authy app to faster identify my credentials.

**Comment by mattwr18** [comment]
@drjakob I started briefly looking into this and here is what I've found so far. There is an article [Adding custom logos in the Authy app](https://support.authy.com/hc/en-us/articles/360002908333-Adding-custom-logos-in-the-Authy-app), which explains how a user can add our icon to their Authy account, but my guess is that you are looking for a way for us as a vendor to add it so that it appears automatically when someone scans the qr code in Authy, correct?

The article continues and answers this question:

> As the vendor of an application, how can I change the logo associated with my application’s account token?

> There are two different scenarios with different solutions. If you are using the Authy API to generate your Authy account token, then you can change the logo in [Twilio Console](https://www.twilio.com/console). If you are not using the Authy API, then the Authy app uses Google Image Search API to find a logo, using your Google Authenticator token’s Issuer name as the default search term. The user can also try other search terms to find a better logo. The search results may not be perfect 100% of the time, because Google Image Search isn’t perfect. If you recently changed your application’s logo, it may take some time for Google to figure out that that is the most relevant logo for your application’s name. In general, we will not change your application’s logo to something different than what is returned by Google.

I looked into it and `Authy API` is deprecated and has been replaced by the [Verify v2 API](https://www.twilio.com/docs/verify/quickstarts/totp). I think now that we use Twilio, it might be possible to share the image we want to use, but I don't think we want to support on Authy as an authenticator.
