### ISSUE TITLE
Bug fixing New Design 

### ISSUE THREAD

**Issue by FrauCsu** [tactilenews/100eyes#1586]
After adding some of the new design features, some smaller issues with the looks came up:

(1) favicon and name
it looks like this for all instances: 
<img width="260" alt="Bildschirm­foto 2023-01-09 um 12 59 20" src="https://user-images.githubusercontent.com/44811680/211303519-9fe6556d-1abe-400a-bf1b-ba44d68a4c73.png">
Please change name from "One hundred eyes" to name of each project, e.g. (staging) "best project" @mattwr18 

(2) color for "Neue Frage stellen" button
it looks like before, but now it seems the button does not use the same kind of pink like the new icons do:
<img width="453" alt="Bildschirm­foto 2023-01-09 um 12 58 59" src="https://user-images.githubusercontent.com/44811680/211303796-03acf010-fc78-4e3b-89bc-cd395ce4f28d.png">
Please check color codes @mattwr18 

(3) button "Einladung verschicken" and button "Neue Frage stellen"
They had the same color pink before, now the first one is darkish blue (new color, new icon), the second continues with old color. Should they look the same, @drjakob ?
<img width="918" alt="Bildschirm­foto 2023-01-09 um 13 06 00" src="https://user-images.githubusercontent.com/44811680/211304298-9914d35b-d35c-4a1b-b4b2-d6f91c9cc5dc.png">

**Comment by mattwr18** [comment]
@FrauCsu
1) Ok, easy fix
2) I talked to @drjakob about this and need to create an issue for it. The pink that the design team used in the icons is not consistent and is not the color we have as our primary color, which is `#f4177a` ... if we want to update our tactile pink, let me know; otherwise, I will update the icons from the design team.
3) I guess it's not a question for me, but it was done as the design called for

**Comment by drjakob** [comment]
3. yes, as proposed by the design team.

**Comment by drjakob** [comment]
2. problem is: for homepage, presentations and logo we use #ff00a0, so I dont know why 100ey.es uses #f4177a as a primary color. lets move to #ff00a0 to be consistent between systems
