### ISSUE TITLE
Contributor profile lies about Telegram onboarding not completed

### ISSUE THREAD

**Issue by roschaefer** [tactilenews/100eyes#1940]
![image](https://github.com/user-attachments/assets/39404456-aabc-4775-817b-1d8689367b94)

But I'm very much onboarded:

![image](https://github.com/user-attachments/assets/9e6ac91a-e255-4316-a90a-6f08393e3f76)

**Comment by mattwr18** [comment]
I think this has to do with the fact that you already onboarded with your telegram id on 01.03.2021. So, what happens is we try to find the sender by the telegram id we receive in the payload of the webhook. In this case, we could find the contributor with id 21, which belongs to the singleton organization. We then would not try to complete the onboarding of the new contributor, with id 148, which is why you have this incomplete state from your screen shot.

**Comment by roschaefer** [comment]
Alrighty
