### ISSUE TITLE
BUG Photo-Counter doesn't work 8for Threema?)

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#813]
The Image-Counter doesn't work in this case. Answer came with Threema.

**Comment by FrauCsu** [comment]
Can we solve this photo counter problem together with the other counter problem #1532 @mattwr18 ?

**Comment by mattwr18** [comment]
As far as I understand, they are not two problems, but one that has had two issues created for. Before creating an issue, it would be helpful to search for existing issues.

If @drjakob did do that and #1532 is not a duplicate, it would be nice to know how they are different. Otherwise, as I suggested, I think we should close the duplicate and see about prioritizing this one.
