### ISSUE TITLE
Automated deployment

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#834]
As beta-testing editor 
I want to have automated deployment to staging environement.

**Comment by tillprochaska** [comment]
@roschaefer Optional, but while you’re at it, you might want to extend the Ansible playbook to automatically set the VPS hostname: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html

By default, Digital Ocean assigns a random hostname to instances (if you don’t explicitly overwrite it while creating the instance). We could easily overwrite it using the [Ansible hostname module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html).

It’s a quick change and might prevent human errors when ssh'ing into instances if you get a shell prompt displaying a human-readable hostname, e.g. `ansible@schweine` instead of `ansible@v1234567890`.

**Comment by tillprochaska** [comment]
See this recent Slack convo: https://tactilenews.slack.com/archives/C010QDQLCKW/p1618911018004400
