### ISSUE TITLE
Filter community by tags

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#955]
As editor
I wanted to filter my community using tags in order to get a better picture of my subcommunities.

**Comment by mattwr18** [comment]
@drjakob @FrauCsu @tillprochaska how do we imagine this looking?
I can imagine that we might want to provide other ways of filtering contributors, for example by channel, by activity, others?
Then maybe we could have a two column layout similar to the contributors show page. I can imagine it looking something like this screen shot. Of course, I didn't spend time to make it look better.

![Screenshot from 2022-10-25 18-18-06](https://user-images.githubusercontent.com/26943915/197827121-9bd00cd3-95e0-42f7-a7a2-7e9d5bc85bb9.png)

**Comment by drjakob** [comment]
I like a pulldown-filterung for tags and one for activity at the bottom of Active/Inactive.

**Comment by mattwr18** [comment]
> I like a pulldown-filterung for tags and one for activity at the bottom of Active/Inactive.

Honestly, I don't think that is a good idea if they plan is to add other filters because it will quickly grow to the point that the filters take up half or more of the above the fold screen. Either way, if we want to work on this, someone needs to take the lead in being responsible for the design. Until then, maybe we can move it out of the current milestone, which is almost over and leave issues that are ready to be worked on?
