### ISSUE TITLE
Show (virtual) number connected with workspace

### ISSUE THREAD

**Issue by drjakob** [tactilenews/100eyes#992]
As editor
I want to see the connected virtual telephone number for my workspace in settings
in order to use it for debugging purposes.

**Comment by phoeinx** [comment]
The settings are already very packed with a lot of customizable information - and especially because this information is not relevant for users in production but rather only for Jakob, Astrid and us devs for debugging purposes, I was wondering if we could find another way for debugging this. As in a way where normal users don't get the extra information (which might start some confusion). 
Especially in regards to Signal number debugging - as this should be a rare occasion (only when we set-up an instance) I think it would be fine to rely on a short check by the devs on the server. (I think the development time now and look up time for the next few instances would definitely sum up.)

**Comment by tillprochaska** [comment]
This has been implemented in #1236.
